### ISSUE TITLE
can you write a readme about how to test or how to run on particular application?

### ISSUE THREAD

**Issue by sayhellohi** [upsj/gpu_selection#1]
well, I am confused how to run the tests
I have ran the unittest, benchmark and benchmark-sort. 
The unittest shows 
unittest:**/gpu_selection/lib/cpu_reference.cpp:130: std::pair<std::vector<unsigned int>, std::vector<unsigned char> > cpu::ssss(const std::vector<T>&, const std::vector<T>&, bool) [with T = float]: Assertion `histogram.size() <= 256 || !write' failed.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
unittest is a Catch v2.7.0 host application.
Run with -? for options

-------------------------------------------------------------------------------
count - float_pair<select_config<10, 11, 9, true, true, false, 8, 10, 10>>
-------------------------------------------------------------------------------
**/gpu_selection/app/test_ssss.cu:70
...............................................................................

**/gpu_selection/app/test_ssss.cu:70: FAILED:
  {Unknown expression after the reported line}
due to a fatal error condition:
  SIGABRT - Abort (abnormal termination) signal

===============================================================================
test cases: 14 | 13 passed | 1 failed
assertions: 28 | 27 passed | 1 failed

Aborted

As for benchmark, it shows:
===============================================================================
No tests ran

So, can you give me some tips? thanks

**Comment by upsj** [comment]
It seems I have only been building the code without assertions enabled. The latest commit should fix that. For the benchmark, you can specify which benchmarks to run as a parameter, i.e. `[test]`, `[full]`, `[full-multionly]`, `[approx]`, `[approx-g]`, `[multi]`, see the corresponding parameter of `TEMPLATE_TEST_CASE` in `app/benchmark.cu`. I will take some time next week to document the details further. Please also note that the code is not production-ready and uses a rather complex template structure, since I wanted to test many possible parameter combinations.

**Comment by sayhellohi** [comment]
> It seems I have only been building the code without assertions enabled. The latest commit should fix that. For the benchmark, you can specify which benchmarks to run as a parameter, i.e. `[test]`, `[full]`, `[full-multionly]`, `[approx]`, `[approx-g]`, `[multi]`, see the corresponding parameter of `TEMPLATE_TEST_CASE` in `app/benchmark.cu`. I will take some time next week to document the details further. Please also note that the code is not production-ready and uses a rather complex template structure, since I wanted to test many possible parameter combinations.

Great work! 

Looking forward your updates. 

Thank you very much.

**Comment by upsj** [comment]
I added a small explanation of the benchmark parameters and output to the README. I hope your issues are now resolved, feel free to reopen if that is not the case.

**Comment by sayhellohi** [comment]
> I added a small explanation of the benchmark parameters and output to the README. I hope your issues are now resolved, feel free to reopen if that is not the case.

Thank you.
